Side bar, UI design, and commits over time visualization
sandiego-rh/explorer pull request #39
Opened 2022-05-06 14:45 UTC by cdolfi

2022-05-13 21:51 UTC, cdolfi commented
More additions made. Can hop on a call to explain

2022-05-17 14:23 UTC, JamesKunstle requested changes

2022-05-17 14:23 UTC, JamesKunstle commented on pages/chaoss.py
> +    if interval == 86400000:
These hard-coded numbers out to be written in the form:
DAY_INTERVAL = 86400000
etc.
at the top of the function to increase legibility.

2022-05-17 14:23 UTC, JamesKunstle commented on pages/overview.py
> +                         {'label': 'Day', 'value': 86400000},
same comment as before- create constant name for these hard-coded values.

2022-05-17 16:31 UTC, merged